### ISSUE TITLE
Warning after pause: energy too low

### ISSUE THREAD

**Issue by igorshirinkin** [yanpaing007/TonTonBot#3]
![swappy-20241004-145444](https://github.com/user-attachments/assets/1d8bc802-c637-4823-afc9-a28e0ce16dac)

**Comment by igorshirinkin** [comment]
https://github.com/yanpaing007/TonTonBot/pull/2#issuecomment-2394023936

**Comment by yanpaing007** [comment]
have you look at their api,afaik available energy only update on thier side if you tap once more,
